### PR TITLE
Add PHP 8.0 runtime

### PR DESCRIPTION
**Pull request by akrabat**
Add a runtime for PHP 8.0. Update the dependencies to the latest versions.

### CODE REVIEW

**Comment by akrabat** [comment]
PHP 8 is now released. Fixed the failing test and using PHP v8.0.1. Ready for review.

**Review by dgrove-oss — APPROVED** [review]
LGTM

**Comment by akrabat** [comment]
What are the next steps to get this merged and released?

**Comment by rabbah** [comment]
@akrabat since no one was assigned, I think it just fell through. Since it was already reviewed (and I also scanned it), I went ahead and merged it. You could have merged it also since you're a maintainer :)

Do you want to cut a release? The steps are documented here: https://github.com/apache/openwhisk-release/blob/master/docs/release_instructions.md.

**Comment by akrabat** [comment]
I'm not used to merging my own PRs :)

I'll have a go at doing a release, probably at the weekend.

**Comment by dgrove-oss** [comment]
sounds good.  ping me if you need any help with making a release @akrabat

**Pull request merged**
